# Generated by Django 5.0.6 on 2024-11-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0001_initial'),
        ('Offers', '0001_initial'),
        ('Slot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycoupon',
            name='Badminton_Slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='Slot.badmintonslot'),
        ),
        migrations.AddField(
            model_name='applycoupon',
            name='Swimming_Slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='Slot.swimmingslot'),
        ),
        migrations.AddField(
            model_name='applycoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Offers.coupon'),
        ),
        migrations.AddField(
            model_name='applycoupon',
            name='turf_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='Slot.turfslot'),
        ),
    ]
