# Generated by Django 5.0.6 on 2024-11-14 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Booking', '0002_initial'),
        ('Offers', '0001_initial'),
        ('Slot', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applycoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='badminton_booking',
            name='badminton_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Slot.badmintonslot'),
        ),
        migrations.AddField(
            model_name='badminton_booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Offers.coupon'),
        ),
        migrations.AddField(
            model_name='badminton_booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='badminton_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.badminton_booking'),
        ),
        migrations.AddField(
            model_name='swimming_booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Offers.coupon'),
        ),
        migrations.AddField(
            model_name='swimming_booking',
            name='swimming_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Slot.swimmingslot'),
        ),
        migrations.AddField(
            model_name='swimming_booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='swimming_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.swimming_booking'),
        ),
        migrations.AddField(
            model_name='turf_booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Offers.coupon'),
        ),
        migrations.AddField(
            model_name='turf_booking',
            name='turf_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Slot.turfslot'),
        ),
        migrations.AddField(
            model_name='turf_booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='turf_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.turf_booking'),
        ),
    ]
