# Generated by Django 5.0.6 on 2024-10-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_remove_swimming_booking_advance_payable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badminton_booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='badminton_booking',
            name='payment_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='badminton_booking',
            name='payment_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='swimming_booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='swimming_booking',
            name='payment_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swimming_booking',
            name='payment_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='turf_booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='turf_booking',
            name='payment_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turf_booking',
            name='payment_status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('successful', 'Successful'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
