# Generated by Django 5.0.6 on 2024-11-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyCoupon',
        ),
    ]
