# Generated by Django 5.0.6 on 2024-10-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_badminton_booking_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimming_booking',
            name='advance_payable',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=10),
        ),
    ]
