# Generated by Django 5.0.6 on 2024-10-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_alter_badminton_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badminton_booking',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='swimming_booking',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='turf_booking',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='ongoing', max_length=20),
        ),
        migrations.CreateModel(
            name='Booking_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('badminton_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.badminton_booking')),
                ('swimming_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.swimming_booking')),
                ('turf_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.turf_booking')),
            ],
        ),
    ]
