# Generated by Django 5.0.6 on 2024-10-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0008_alter_badminton_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_history',
            name='advance_payable',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
