# Generated by Django 5.0.6 on 2024-11-14 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_applycoupon'),
        ('Slot', '0012_alter_badmintonslot_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applycoupon',
            name='Badminton_Slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='Slot.badmintonslot'),
        ),
        migrations.AddField(
            model_name='applycoupon',
            name='Swimming_Slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='Slot.swimmingslot'),
        ),
        migrations.AlterField(
            model_name='applycoupon',
            name='turf_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_coupons', to='Slot.turfslot'),
        ),
    ]
