# Generated by Django 5.0.6 on 2024-10-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='SportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('4A Side', '4A Side'), ('6A Side', '6A Side'), ('Swimming Adult', 'Swimming Adult')], max_length=50)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turf.sports')),
            ],
        ),
        migrations.CreateModel(
            name='SlotEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilities', to='Turf.sportfield')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turf.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='Turf.sportfield')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turf.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='turf_images/')),
                ('rating', models.FloatField(default=0.0)),
                ('available_offers', models.ManyToManyField(blank=True, null=True, to='Offers.coupon')),
                ('facilities', models.ManyToManyField(to='Turf.facility')),
                ('sports', models.ManyToManyField(blank=True, null=True, to='Turf.sports')),
            ],
        ),
        migrations.AddField(
            model_name='sportfield',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Turf.turf'),
        ),
    ]
