# Generated by Django 5.0.6 on 2024-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
    ]
