# Generated by Django 5.0.6 on 2024-10-03 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0002_price_duration_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sloteligibility',
            name='field',
        ),
        migrations.AddField(
            model_name='sloteligibility',
            name='Turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Turf.turf'),
        ),
    ]
