# Generated by Django 5.0.6 on 2024-10-04 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0003_remove_sloteligibility_field_sloteligibility_turf'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='Turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Turf.turf'),
        ),
    ]
