# Generated by Django 5.0.6 on 2024-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offers', '0001_initial'),
        ('Turf', '0005_alter_price_turf_alter_sloteligibility_turf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='available_offers',
            field=models.ManyToManyField(blank=True, to='Offers.coupon'),
        ),
    ]
