# Generated by Django 5.0.6 on 2024-10-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0006_alter_turf_available_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='Turf',
            new_name='turf',
        ),
        migrations.AddField(
            model_name='turf',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
