# Generated by Django 5.0.6 on 2024-10-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0008_turf_user_turf_latitude_turf_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='days_of_week',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Mon', max_length=21),
        ),
    ]
