# Generated by Django 5.0.6 on 2024-10-18 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0009_price_days_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turfs', to='Turf.turf'),
        ),
    ]
