# Generated by Django 5.0.6 on 2024-10-19 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0010_timeslot_turf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='Turf.turf'),
        ),
    ]
