# Generated by Django 5.0.6 on 2024-11-09 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0013_sports_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Turf.turf'),
        ),
    ]
