# Generated by Django 5.0.6 on 2024-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turf', '0014_alter_review_turf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='duration',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=4, null=True),
        ),
    ]
