# Generated by Django 5.0.6 on 2024-11-14 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Slot', '0002_initial'),
        ('Turf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='badmintonslot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slothistory',
            name='badminton_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Slot.badmintonslot'),
        ),
        migrations.AddField(
            model_name='slothistory',
            name='turf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Turf.turf'),
        ),
        migrations.AddField(
            model_name='slothistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='swimmingsession',
            unique_together={('start_time', 'end_time')},
        ),
        migrations.AddField(
            model_name='swimmingslot',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Turf.sportfield'),
        ),
        migrations.AddField(
            model_name='swimmingslot',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Slot.swimmingsession'),
        ),
        migrations.AddField(
            model_name='swimmingslot',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turf.turf'),
        ),
        migrations.AddField(
            model_name='swimmingslot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slothistory',
            name='swimming_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Slot.swimmingslot'),
        ),
        migrations.AddField(
            model_name='turfslot',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Turf.sportfield'),
        ),
        migrations.AddField(
            model_name='turfslot',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Turf.turf'),
        ),
        migrations.AddField(
            model_name='turfslot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slothistory',
            name='turf_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Slot.turfslot'),
        ),
        migrations.AlterUniqueTogether(
            name='swimmingslot',
            unique_together={('session', 'date', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='turfslot',
            unique_together={('turf', 'date', 'start_time', 'end_time', 'field')},
        ),
    ]
