# Generated by Django 5.0.6 on 2024-10-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0002_alter_turfslot_unique_together'),
        ('Turf', '0005_alter_price_turf_alter_sloteligibility_turf_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swimmingslot',
            unique_together={('session', 'date', 'field')},
        ),
        migrations.RemoveField(
            model_name='swimmingslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='swimmingslot',
            name='start_time',
        ),
    ]
