# Generated by Django 5.0.6 on 2024-10-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0004_remove_swimmingslot_is_available_slothistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SlotHistory',
        ),
    ]
