# Generated by Django 5.0.6 on 2024-10-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0006_slothistory'),
        ('Turf', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='slothistory',
            name='turf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Turf.turf'),
        ),
    ]
