# Generated by Django 5.0.6 on 2024-11-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0008_alter_slothistory_total_price_alter_slothistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badmintonslot',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='turfslot',
            name='coupon',
        ),
    ]
