# Generated by Django 5.0.6 on 2024-11-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0009_remove_badmintonslot_coupon_remove_turfslot_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimmingslot',
            name='coupon',
        ),
    ]
