# Generated by Django 5.0.6 on 2024-11-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slot', '0010_remove_swimmingslot_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='badmintonslot',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='swimmingslot',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='turfslot',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
