# Generated by Django 5.0.6 on 2024-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_usermodel_max_otp_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_image/'),
        ),
    ]
