# Generated by Django 5.0.6 on 2024-10-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_usermodel_role_alter_usermodel_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
